//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public int U_id { get; set; }
        public string U_name { get; set; }
        public int U_groupId { get; set; }
    
        public virtual T_group T_group { get; set; }
    }
}
